main_project/charts/urls.py
from django.urls import path,include,re_path
from charts import views
from django.conf.urls import url

app_name='charts'

urlpatterns=[
    url(r'^index1/',views.index1,name='index1'),
    url(r'^get_feedback/',views.get_feedback,name='get_feedback'),
    url(r'^send_email/', views.send_email, name='send_email'),
    #url(r'^$', views.index, name='index'),
    url(r'^form/', views.form, name='form'),
    url(r'^feedback/', views.feedback, name='feedback'),
    url(r'^report/', views.Report, name='report'),
    #url(r'^api/chart/data/$', views.ChartData.as_view(),name='api_data'),
    url(r'^feedback_response/', views.feedback_response, name='feedback_responses'),
]

main_project/main_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from organiser_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('evoting.urls')),
    path('evoting/', include('evoting.urls')),
    path('organiser_app/',include('organiser_app.urls')),
    path('api/candidate/',views.candidateListView.as_view()),
    path('charts/', include('charts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main_project/organiser_app/urls.py
from django.urls import path
from . import views
from evoting import views as user_views

app_name="organiser_app"

urlpatterns=[

        path('index/',views.index,name="index"),
        path('select_region_page/',views.select_region_page,name="select_region_page"),
        path('candidate/',views.candidate_page,name='candidate'),
        path('index1/',views.main_page,name='mainpage'),
        path('election/',views.election,name="election"),
        path('addelection/',views.addelection,name="addelection"),
        path('voter_region_page/search_voter', views.search_voter, name='search_voter'),
        path('voter_region_page/add_voter/', views.add_voter, name='add_voter'),
        path('voter_region_page/<int:pk>', views.voter_region_page, name='voter_region_page'),
        path('view/<int:pk>',views.candidate_view,name='candidate_view'),
        path('edit/<int:pk>',views.candidate_update,name='candidate_edit'),
        path('view1/<int:pk>',views.voter_view,name='voter_view'),
        path('edit1/<int:pk>',views.voter_update,name='voter_update'),
        path('party/',views.party,name="party"),
        path('region-candidate/<int:pk>',views.reg_candidate,name="region-candidate"),
        path('party-candidate/<str:pk>',views.party_candidate,name="party-candidate"),
        path('election-candidate/<int:pk>',views.election_candidate,name="election-candidate"),
        path('election_edit/<int:pk>',views.election_update,name="election_edit"),
        path('candidate-election/<int:pk>',views.candidate_election,name="candidate-election"),
        path('logout/', user_views.user_logout, name='evoting-logout'),
        path('srccandidate/',views.srchcandidate,name='srccandidate')
]

main_project/organiser_app/forms.py
from django import forms
from . models import Candidate,Voter,Election
from django.core import validators
import datetime


region_options = (

 ('0','AndhraPradesh') ,
 ('1','Bihar') ,
 ('2','karnataka'),
 ('3','Tamilnadu' ),
 ('4','Kerela') ,
 ('5','UttarPradesh'),
 ('6','WestBengal') ,
 ('7','MadhyaPradesh') ,
 ('8','Haryana') ,
 ('9','Assam'),
 ('10','All')

)

party_options=(

    ('BJP','Bhartiya Janta Party'),
    ('CPI','Communist Party of India'),
    ('INC','Indian National Congress'),
    ('AAP','Aam Aadmi Party') ,
    ('TDP','Telugu Desam Party'),
    ('SS','Shiv Sena') ,
    ('TRS','Telangana Rashtra Samithi'),
    ('JD','Janata Dal') ,
    ('SP','Samajwadi Party') ,
   ('RJD', 'Rashtriya Janata Dal')

)





class Candidateform(forms.ModelForm):
    candidate_dob = forms.DateField(widget=forms.SelectDateWidget(years=range(1920, 1994)))

    class Meta:
        model = Candidate
        fields = ('candidate_name','candidate_fname','candidate_party','candidate_region','candidate_gender','candidate_email','candidate_dob','candidate_aadhar','profile_pic')



class Electionform(forms.ModelForm):
    date_of_start = forms.DateField(widget=forms.SelectDateWidget(),initial=datetime.date.today)
    date_of_end = forms.DateField(widget=forms.SelectDateWidget(),initial=datetime.date.today)
    class Meta():
        model=Election
        fields=('election_type','election_year','date_of_start','date_of_end', 'candidates')



class Voterform(forms.ModelForm):
    voter_dob = forms.DateField(widget=forms.DateInput(attrs={'id':'date','type':'date',}))
    voter_age = forms.IntegerField(widget=forms.NumberInput(attrs={'id':'age'}))

    class Meta:
        model = Voter
        fields = '__all__'


class RegionForm(forms.Form):
    select_region = forms.ChoiceField(choices=region_options)

class PartyForm(forms.Form):
    select_party=forms.ChoiceField(choices=party_options)

main_project/organiser_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . forms import *
from . models import *
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from  organiser_app.serializers import  CandidateSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.contrib import messages
import schedule
import time
import datetime

region_options={

 '0':'AndhraPradesh' ,
 '1':'Bihar' ,
 '2':'karnataka',
 '3':'Tamilnadu' ,
 '4':'Kerela' ,
 '5':'UttarPradesh',
 '6':'WestBengal' ,
 '7':'MadhyaPradesh' ,
 '8':'Haryana' ,
 '9':'Assam',
 '10':'All'

}


# Create your views here.
@login_required
def party(request):
    party_form = PartyForm()
    context = {'party_form':party_form}
    return render(request, 'organiser_app/party.html',context)



@login_required
def index(request):
    region_form = RegionForm()
    context = {'region_form':region_form}
    return render(request, 'organiser_app/index.html',context)

@login_required
def srchcandidate(request):
    candidate_id=request.POST.get('Candidateid')

    try:
        object = Candidate.objects.get(candidate_id=candidate_id)
        region=region_options[object.candidate_region]
        context = {'object': object,'region':region}
        return render(request, 'organiser_app/candidate_info.html', context=context)
    except:
        message ='Sorry,' + 'Candidate Id "' + str(candidate_id) + '" does not exist.'
        context = {'message': message}
        return render(request, 'organiser_app/candidate_info.html', context=context)

    return render(request,'organiser_app/index.html',context)

@login_required
def candidate_page(request):

    if request.method =="POST":
        candidate_form=Candidateform(request.POST, request.FILES)

        if candidate_form.is_valid():

            object=candidate_form.save()
            region=region_options[object.candidate_region]
            context={'object':object,'region':region}
            return render(request,'organiser_app/candidate_info.html',context)

        else:
            print(candidate_form.errors)

    else:
        candidate_form=Candidateform()

    return render(request, 'organiser_app/addcandidate.html', {'candidate_form':candidate_form })

@login_required
def main_page(request):
    return render(request,'organiser_app/index1.html')

#change

@login_required
def election(request):
    region=[]
    election_instance=Election.objects.all()
    for election in election_instance:
        region.append(Election_region.objects.get(election=election.election_id))
    election_region = zip(election_instance, region)

    context={'election_region':election_region}
    return render(request,'organiser_app/election.html',context)

# ------------------------------------Voter Code--------------------------------------------

@login_required
def add_voter(request):

    if request.method == 'POST':

        voter_form = Voterform(data=request.POST)

        if voter_form.is_valid():

                voter_form.save(commit=True)
                message = 'Voter is added successfully!'
                return render(request, 'organiser_app/add_voter.html', {'voter_form': voter_form, 'message': message})

        else:
            print(voter_form.errors)
    else:
        voter_form = Voterform()

    return render(request, 'organiser_app/add_voter.html', {'voter_form':voter_form})

@login_required
def select_region_page(request):

    region_form = RegionForm()

    context = {'region_form':region_form}

    return render(request, 'organiser_app/select_region.html',context)

@login_required
def search_voter(request):

    if request.method == 'POST':
        voterid = request.POST.get('voterid')
        try:
            voter = Voter.objects.get(voter_id=voterid)
            context = {'voter': voter}
            return render(request, 'organiser_app/search_results.html', context=context)
        except:
            message = 'Voter Id "' + str(voterid) + '" does not exist.'
            context = {'message': message}
            return render(request, 'organiser_app/search_results.html', context=context)

    return render(request, 'organiser_app/search_results.html')

@login_required
def voter_region_page(request,pk):
    template_name='organiser_app/voters_list.html'
    if pk is 10:
        voters=Voter.objects.all()
    else:
        voters = Voter.objects.filter(voter_region=pk)
    context = {'voters':voters}
    return render(request,template_name,context)

@login_required
def voter_view(request, pk):
    template_name = 'organiser_app/voter_info.html'
    voter=get_object_or_404(Voter, pk=pk)
    region = region_options[voter.voter_region]
    context = {'voter': voter, 'region': region}
    return render(request, template_name, context=context)

@login_required
def voter_update(request, pk):
    template_name = 'organiser_app/update_voter_form.html'
    voter = get_object_or_404(Voter, pk=pk)
    voter_form = Voterform(request.POST or None, instance=voter)
    if request.method == 'POST':
        if voter_form.is_valid():
            voter_form.save()
            message = 'Voter Id "' + str(voter.voter_id) + '" is updated successfully!'
            return render(request, template_name, {'voter_form': voter_form, 'message': message})
    return render(request, template_name, {'voter_form': voter_form})


def search_voter(request):

    if request.method == 'POST':
        voterid = request.POST.get('voterid')
        try:
            voter = Voter.objects.get(voter_id=voterid)
            context = {'voter': voter}
            return render(request, 'organiser_app/search_results.html', context=context)
        except:
            message = 'Voter Id "' + str(voterid) + '" does not exist.'
            context = {'message': message}
            return render(request, 'organiser_app/search_results.html', context=context)

    return render(request, 'organiser_app/search_results.html')


#-------------------------------------------End Voter Code---------------------------------------------
#change

@login_required
def addelection(request):
    if request.method=="POST":
        addelection_form=Electionform(data=request.POST)

        if addelection_form.is_valid():
            election_instance = addelection_form.save()

            for candidate in election_instance.candidates.all():

                candidate_election_instance = Candidate_election()
                candidate_election_instance.candidate = candidate
                candidate_election_instance.election = election_instance
                candidate_election_instance.save()

            if election_instance.election_type == 'P':

                election_region_instance=Election_region()
                election_region_instance.region="All"
                election_region_instance.election=election_instance
                election_region_instance.save()

            if election_instance.election_type=='A':
                election_region_instance=Election_region()
                region=request.POST['statelist']
                print(region)
                election_region_instance.region=region
                election_region_instance.election=election_instance
                election_region_instance.save()

            region=[]
            election_instance=Election.objects.all()
            for election in election_instance:
                region.append(Election_region.objects.get(election=election.election_id))
            election_region = zip(election_instance, region)

            context={'election_region':election_region}
            return render(request,'organiser_app/election.html',context)

        else:
            print(addelection_form.errors)
    else:
        addelection_form=Electionform()

    return render(request,'organiser_app/election_form.html',{'addelection_form':addelection_form })

@login_required
def candidate_view(request,pk):
    template_name='organiser_app/candidate_detail.html'
    candidate=get_object_or_404(Candidate,pk=pk)
    region=region_options[candidate.candidate_region]
    context={'object':candidate, 'region':region}
    return render(request,template_name,context=context)

@login_required
def candidate_update(request,pk):
    template_name='organiser_app/candidate_form.html'
    candidate=get_object_or_404(Candidate,pk=pk)
    form=Candidateform(request.POST or None,instance=candidate)
    if request.method=="POST":

        if form.is_valid():
            object=form.save()

            region=region_options[object.candidate_region]
            context={'object':object,'region':region}
            return render(request,'organiser_app/candidate_info.html',context)

            #return HttpResponseRedirect(reverse( organiser_app:candidate_edit 'form.candidate_id ))

    return render(request,template_name,{'form':form})

#change
@login_required
def reg_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    if pk is 10:
        candidates=Candidate.objects.all()

    else:
        candidates=Candidate.objects.filter(candidate_region=pk)

    context={'candidates':candidates}
    return render(request,template_name,context)

@login_required
def party_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    candidates=Candidate.objects.filter(candidate_party=pk)
    context={'candidates':candidates}
    return render(request,template_name,context)


@login_required
def election_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    candidates_ele=Candidate_election.objects.filter(election=pk)
    list_candidate=[]
    for candi in candidates_ele:
        list_candidate.append(candi.candidate)

main_project/templates/organiser_app/election.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


      <style>
         a:hover {
         background:#263238;
         }
         table {
         border-collapse: collapse;
         border-radius: 1em;
         overflow: hidden;
         }
      </style>
      <title>organiser_region</title>
   </head>


   <body style="position: relative; padding-top: 20px;">
      <nav class="navbar fixed-top container-fluid navbar-expand-lg navbar-light bg-dark">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
            <p style="color:white; font-size:30px;margin:5px"><a style="color:white;text-decoration: none" href="{% url 'evoting-home' %}" >E-Voting </a></p>
         </div>
         <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:addelection' %}" style="font-size:26px">Add Election <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:evoting-logout'%}" style="font-size:26px">Logout <span class="sr-only">(current)</span></a>
            </li>
         </ul>
      </nav>


      <div class="shadow-lg p-3 mb-5 bg-white rounded" style="margin-top:50px" id="elections">

         <input class="search float-right" style="border-radius:20px;padding:5px;margin-bottom:10px;border:2px solid black;outline:none;"placeholder="Enter Election Id" />
         <table class="table table-dark " style="margin: 20px auto;">
            <thead class="thead thead-light " style="text-align: center">
               <th class="eid"> Election Id</th>
               <th class="type"> Election Type</th>
               <th > Election Year</th>
               <th> Election DoS</th>
               <th> Election DoE</th>
               <th class="status"> Election Status</th>
               <th>Region</th>
               <th> Info </th>
               <th>Update</th>
            </thead>
            <tbody class="list">
               {% for i,j in election_region %}
               <tr style="text-align: center">
                  <td class="eid">{{ i.election_id}}</td>
                  <td class="type">{{ i.election_type}}</td>
                  <td >{{ i.election_year}}</td>
                  <td>{{ i.date_of_start}}</td>
                  <td>{{ i.date_of_end}}</td>
                  <td class="status">{{ i.status}}</td>
                    <td> {{j}}</td>
                  <td><a href="{% url "organiser_app:election-candidate" i.election_id %}" >Click</a></td>
                  <td><a href="{% url "organiser_app:election_edit" i.election_id %}" >Click</a></td>
               </tr>
               {% endfor %}
            </tbody>
         </table>

      </div>


      <!-- Optional JavaScript -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="{% static 'javascript/list.min.js' %}" ></script>

      <script>
         var options = {
           valueNames: ['eid','type','status']
         };

         var musiclibraryList = new List('elections', options);
      </script>


   </body>
</html>

main_project/templates/organiser_app/index1.html
{% load staticfiles %}
<!Doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


      <style>
         a:hover {
         background:#263238;
         }
         body {margin:2rem;}
         @media (min-width: 544px) {
         }
         @media (min-width: 768px) {
         }
         /* Large devices (desktops, 992px and up) */
         @media (min-width: 992px) {
         }
         /* Extra large devices (large desktops, 1200px and up) */
         @media (min-width: 1200px) {
         }
         @media (max-width: 950px) {
         }
      </style>
      <title>organiser_main</title>
   </head>


   <body>
      <nav class="navbar fixed-top container-fluid navbar-expand-lg navbar-light bg-dark">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
            <p style="color:white; font-size:30px;margin:5px"><a style="color:white;text-decoration: none" href="{% url 'evoting-home' %}" >E-Voting </a></p>
         </div>

         <ul class=" nav navbar-nav navbar-right">
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:election' %}" style="font-size:26px">Election <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:party' %}" style="font-size:26px">Party <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
             <li class="nav-item active">
               <a class="nav-link text-white " href="{% url 'charts:feedback_responses' %}" style="font-size:26px">Feedbacks <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
               <a class="nav-link text-white " href="{% url 'organiser_app:evoting-logout' %}" style="font-size:26px">Logout <span class="sr-only">(current)</span></a>
            </li>
         </ul>
      </nav>


      <div class="container-fluid h-100 text-dark" style="margin-top:175px">
         <div class="row justify-content-center align-items-center h-100">
            <div class ="row">
               <div class="card sm-6" style="width: 18rem;">
                  <img class="card-img-top" src="{% static "images/neta.png"%}" alt="Card image cap" width="50" height="250">
                  <div class="card-body">
                     <a href="{% url 'organiser_app:index' %}" class="btn btn-primary" style="background-color:#424242">Candidates</a>
                  </div>
               </div>
               <div class="card sm-6" style="width: 18rem;margin-left:50px">
                  <img class="card-img-top" src="{% static "images/voters.jpeg"%}" alt="Card image cap" width="50" height="250">
                  <div class="card-body">
                     <a href="{% url 'organiser_app:select_region_page' %}" class="btn btn-primary" style="background-color:#424242">Voters</a>
                  </div>
               </div>
            </div>
         </div>
         <!-- /.container -->
         <!-- /.container -->
      </div>
      </div>


      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


      <script>
         $(document).ready(function() {
          // executes when HTML-Document is loaded and DOM is ready

           $( ".card" ).hover(
           function() {
             $(this).addClass('shadow-lg').css('cursor', 'pointer');
           }, function() {
             $(this).removeClass('shadow-lg');
           }
         );

         // document ready
         });

      </script>
   </body>
</html>

main_project/templates/organiser_app/voters_list.html
<!DOCTYPE  html>
{% load staticfiles %}
{% load widget_tweaks %}

<html lang="en">
<head>
    <title>Voters List.</title>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            background-image:url({% static 'images/back.jpg' %});
            background-repeat: no-repeat;
            height:100%; background-attachment:fixed;
        }
        .container-fluid {
            box-shadow: 0px 0px 15px 8px white;
            margin-top: 100px;
            padding: 20px;
            width: 70%;
        }
        #myInput {
            width: 100%; font-size: 16px;
            padding: 12px 20px 12px 40px;
            border: 2px solid black;
            margin-bottom: 12px;
        }

    </style>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg bg-dark" >
        <div class="navbar-collapse " id="navbarSupportedContent">
            <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
            <p style="color:white; font-size:25px;margin:5px"><a style="color:white;text-decoration: none" href="{% url 'evoting-home' %}" >E-Voting </a></p>
        </div>

        <ul class="navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:mainpage' %}" style="font-size:25px">Mainpage</a>
            </li>
            <li>
                <p class="text-white " style="font-size:25px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:add_voter' %}" style="font-size:26px">Add Voters</a>
            </li>
            <li>
                <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:select_region_page' %}" style="font-size:26px">Regions</a>
            </li>
            <li>
                <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:evoting-logout' %}" style="font-size:26px">Logout</a>
            </li>
        </ul>
    </nav>
    <div class="container-fluid">
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search by Voter Id..">

        <table class="table" id="myTable">
            <thead class="table-dark">
                <th> Voter Id</th>
                <th> Voter Name</th>
                <th> Voter email</th>
                <th> Voter gender</th>
                <th colspan="2">Actions</th>
            </thead>
            {% for voter in voters %}
            <tr class="table">
                <td>{{ voter.voter_id}}</td>
                <td>{{ voter.voter_name}}</td>
                <td>{{ voter.voter_email}}</td>
                <td>{{ voter.voter_gender}}</td>
                <td><a href="{% url 'organiser_app:voter_view' voter.voter_id %}">Info</a></td>
                <td><a href="{% url 'organiser_app:voter_update' voter.voter_id %}">Edit</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>


<script>
function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>