main_project/charts/urls.py
from django.urls import path,include,re_path
from charts import views
from django.conf.urls import url

app_name='charts'

urlpatterns=[
    url(r'^index1/',views.index1,name='index1'),
    url(r'^get_feedback/',views.get_feedback,name='get_feedback'),
    url(r'^send_email/', views.send_email, name='send_email'),
    #url(r'^$', views.index, name='index'),
    url(r'^form/', views.form, name='form'),
    url(r'^feedback/', views.feedback, name='feedback'),
    url(r'^report/', views.Report, name='report'),
    #url(r'^api/chart/data/$', views.ChartData.as_view(),name='api_data'),
    url(r'^feedback_response/', views.feedback_response, name='feedback_responses'),
]

main_project/main_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from organiser_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('evoting.urls')),
    path('evoting/', include('evoting.urls')),
    path('organiser_app/',include('organiser_app.urls')),
    path('api/candidate/',views.candidateListView.as_view()),
    path('charts/', include('charts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main_project/organiser_app/urls.py
from django.urls import path
from . import views
from evoting import views as user_views

app_name="organiser_app"

urlpatterns=[

        path('index/',views.index,name="index"),
        path('select_region_page/',views.select_region_page,name="select_region_page"),
        path('candidate/',views.candidate_page,name='candidate'),
        path('index1/',views.main_page,name='mainpage'),
        path('election/',views.election,name="election"),
        path('addelection/',views.addelection,name="addelection"),
        path('voter_region_page/search_voter', views.search_voter, name='search_voter'),
        path('voter_region_page/add_voter/', views.add_voter, name='add_voter'),
        path('voter_region_page/<int:pk>', views.voter_region_page, name='voter_region_page'),
        path('view/<int:pk>',views.candidate_view,name='candidate_view'),
        path('edit/<int:pk>',views.candidate_update,name='candidate_edit'),
        path('view1/<int:pk>',views.voter_view,name='voter_view'),
        path('edit1/<int:pk>',views.voter_update,name='voter_update'),
        path('party/',views.party,name="party"),
        path('region-candidate/<int:pk>',views.reg_candidate,name="region-candidate"),
        path('party-candidate/<str:pk>',views.party_candidate,name="party-candidate"),
        path('election-candidate/<int:pk>',views.election_candidate,name="election-candidate"),
        path('election_edit/<int:pk>',views.election_update,name="election_edit"),
        path('candidate-election/<int:pk>',views.candidate_election,name="candidate-election"),
        path('logout/', user_views.user_logout, name='evoting-logout'),
        path('srccandidate/',views.srchcandidate,name='srccandidate')
]

main_project/charts/models.py
from django.utils import timezone
from django.db import models
from organiser_app.models import *

# Create your models here.
class Gen(models.Model):
    party = models.CharField(unique=True, max_length=10)
    total = models.IntegerField(default='0')

    def __str__(self):
        return self.party + str(self.total)

class Feedback(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    feedback = models.CharField(max_length=300, null=False)
    rating=models.CharField(max_length=10,null=False)
    date=models.DateTimeField(default=timezone.now)

    def str(self):
        return self.name


class Report_data(models.Model):
    name1 = models.CharField(max_length=30, null=False)
    email = models.EmailField(max_length=40, null=False)
    report = models.CharField(max_length=300, null=False)
    rating=models.CharField(max_length=10,null=False)
    def str(self):
        return self.name1

main_project/charts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Gen,Feedback, Report_data
from organiser_app.models import *
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.
from django.template import RequestContext
# from django.shortcuts import render_to_response

from django.http import JsonResponse
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response


def Report(request):
    return render(request, "graphs/report.html")


def feedback(request):
    return render(request, "graphs/feedback.html")


def form(request):
    return render(request, "graphs/index3.html")


def get_feedback(request):
    print("Request Object: {}".format(request.POST))
    name = request.user.username
    feedback = request.POST['feedback']
    rating = request.POST['rating']
    FeedbackData = Feedback.objects.create(name=name, feedback=feedback,rating=rating)
    FeedbackData.save()
    return HttpResponse("Thanks for your feedback")


def index1(request):
    print("Request Object: {}".format(request.POST))
    party = request.POST['party']
    total = request.POST['total']
    Userlog = Gen.objects.create(party=party, total=total)
    Userlog.save()
    return HttpResponse("Your data is stored")


def index(request):
    return render(request, 'graphs/charts.html')


def send_email(request):
    name1 = request.user.username
    email = request.user.email
    report = request.POST['report']
    rating = request.POST['rating']
    Report_data1 = Report_data.objects.create(name1=name1, email=email, report=report,rating='rating')
    Report_data1.save()
    subject = 'Custromers report'
    message = (
        'Please check the customer s feedback sent to you \n Name : {} ;\n Email : {} ;\n Feedback : {} ;\n Star Ratings(Out of 5): {} '.format(name1,
                                                                                                                email,
                                                                                                                report,rating))
    email_from = settings.EMAIL_HOST_USER
    recipient_list = ['nehul.r17@iiits.in']
    send_mail(subject, message, email_from, recipient_list)
    return HttpResponse("Thanks , your report has been sent")

def feedback_response(request):
    fresponse=Feedback.objects.all()
    data={'fresponse':fresponse}
    return render(request,'graphs/feedback_responses.html',data)

main_project/templates/graphs/charts.html
{% extends 'graphs/maincharts.html' %}

<script>
{% block jquery %}

data = {{ data|safe }};
console.log(data);
console.log("HI");
for(var i=0;i<10;i++)
{
    value=data[i];
    labels=value.labelsdata;
    defaultData=value.defaultdata;
    console.log(labels);
    console.log(defaultData);
    setChart(labels,defaultData,i);


}

function setChart(labels,defaultData,i){
    var str = ("myChart"+i.toString());
    console.log(str);
    var ctx2 = document.getElementById(str);
    console.log(ctx2);
    var myChart = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: 'Number of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'darkred','darkblue','darkorange',
                'darkmagneta','darkgoldenrod','deeppink',
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});


}
            // var ctx = document.getElementById("myChart");
      {% endblock jquery %}
    </script>
{%  block content %}
        <div style="height: 250px"></div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Andhra Pradesh</h2>
            <canvas id="myChart0" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Bihar</h2>
            <canvas id="myChart1" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Karnataka</h2>
            <canvas id="myChart2" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Tamil Nadu</h2>
            <canvas id="myChart3" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Kerela</h2>
            <canvas id="myChart4" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Uttar Pradesh</h2>
            <canvas id="myChart5" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">West Bengal</h2>
            <canvas id="myChart6" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Madhya Pradesh</h2>
            <canvas id="myChart7" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Haryana</h2>
            <canvas id="myChart8" width="90" height="50"></canvas>
        </div>
        <div class="jumbotron" id="chart">
            <h2 style="color:red;text-align:center">Assam</h2>
            <canvas id="myChart9" width="90" height="50"></canvas>
        </div>

        <div style="height: 200px"></div>
{% endblock content %}

main_project/templates/graphs/feedback.html
{% extends 'voters/base.html' %}
{% load staticfiles %}
{% block head %}

    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}">
{% endblock head %}
{%  block body %}

<div class="feedback-page">
<marquee id="slider" onMouseOver="this.stop()" onMouseOut="this.start()">Fill in the Feedback Form</marquee><br>
<div class="form">
    <form class="feedback-form" action="{% url 'charts:get_feedback' %}" method="POST">
       {% csrf_token %}
     <h1>Feedback Page</h1><br>
      <label for="feedback">Feedback</label>
        <textarea rows="10" id="feedback" name="feedback" placeholder="Enter Feedback"/></textarea>
      <label for="stars">Rate Stars:</label><br>
       <fieldset class="rating">
        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Satisfactory - 3 stars"></label>
        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Need to Improve - 2 stars"></label>
        <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Poor - 1 star"></label>
      </fieldset>
      <button>Submit</button><br><br>
    </form>
  </div>
</div>
<div style="height: 400px"></div>
{% endblock body %}

main_project/templates/graphs/feedback1.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
    <title>
        Feedback
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body  background="{% static 'graphs/images/bg1.jpg' %}"  >
<div class="feedback-page">
  <div class="form">
    <form class="feedback-form" action="{% url 'charts:get_feedback' %}" method="POST">
       {% csrf_token %}
     <h1>Feedback Page</h1><br>
      <label for="name1">Name:</label>
      <input type="text" id="name" name="name1" placeholder="Name"/>
      <label for="feedback">Feedback</label>
        <textarea rows="20" id="feedback" name="feedback" placeholder="Enter Feedback"/></textarea>
      <label for="stars">Rate Stars:</label><br>
       <fieldset class="rating">
        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Satisfactory - 3 stars"></label>
        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Need to Improve - 2 stars"></label>
        <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Poor - 1 star"></label>
      </fieldset>
      <button>Submit</button>
    </form>
  </div>
</div>
</body>
</html>

main_project/templates/graphs/feedback_responses.html
{% load staticfiles %}
<!Doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


      <style>
         a:hover {
         background:#263238;
         }
         body {margin:2rem;}
       </style>
      <title>organiser_main</title>
    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}">
</head>
<body>
      <nav class="navbar fixed-top container-fluid navbar-expand-lg navbar-light bg-dark">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
            <a href=" "  style="color:white; font-size:30px;margin:5px">E-Voting</a>
         </div>

         <ul class=" nav navbar-nav navbar-right">
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:election' %}" style="font-size:26px">Election <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
               <a class="nav-link text-white" href="{% url 'organiser_app:party' %}" style="font-size:26px">Party <span class="sr-only">(current)</span></a>
            </li>
            <li>
               <p class="text-white " style="font-size:26px;margin:5px">|</p>
            </li>
            <li class="nav-item active">
               <a class="nav-link text-white " href="#" style="font-size:26px">Logout <span class="sr-only">(current)</span></a>
            </li>
         </ul>
      </nav>
<br><br>
<div class="container">
<marquee id="slider" onMouseOver="this.stop()" onMouseOut="this.start()">Feedbacks Uploaded are:</marquee><br>
    </div>
{% for data in fresponse %}
<br><br>
    <main role="main" class="container">
    <div class="row">
        <div class="col md-5">
        <article class="media content-section" style="background-color:rgba(0, 206, 209, 0.8)">
        <div class="media-body">
            <div class="article-metadata">
                <br>
                <h3><center><p class ="article-content">{{data.feedback}}</p></center></h3>
                <center>Feedback by {{data.name}} on <small class="text-muted">{{data.date}}</small></center><br>

            </div>
        </div>
        </div>
    </article>
    </div>
    </main>
{% endfor %}

<div style="height: 400px"></div>
</body>
</html>

main_project/templates/graphs/feedback_responses1.html
{% extends 'voters/base.html' %}
{% load staticfiles %}
{% block head %}

    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}">
{% endblock head %}
{%  block body %}

<br><br>
<div class="container">
<marquee id="slider" onMouseOver="this.stop()" onMouseOut="this.start()">Feedbacks Uploaded are:</marquee><br>
    </div>
{% for data in fresponse %}
<br><br>
    <main role="main" class="container">
    <div class="row">
        <div class="col md-5">
        <article class="media content-section" style="background-color:rgba(0, 206, 209, 0.8)">
        <div class="media-body">
            <div class="article-metadata">
                <br>
                <h3><center><p class ="article-content">{{data.feedback}}</p></center></h3>
                <center>Feedback by {{data.name}} on <small class="text-muted">{{data.date}}</small></center><br>

            </div>
        </div>
        </div>
    </article>
    </div>
    </main>
{% endfor %}

<div style="height: 400px"></div>
{% endblock body %}

main_project/templates/graphs/index2.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
  <head>
    <title>
      Django 2
    </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include 'base/css.html' %}
    {% include 'base/bootstrap_defaults.html' %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body background="{% static 'graphs/images/black.jpg' %}">
      <section id="page-header">
        <img id="logo" src="{% static 'graphs/images/evote.jpg' %}">
        <h1 id="heading">IIITS Online Voting Commision</h1>
      </section>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li><a href="#">Home</a></li>
              <li class="active"><a href="#chart">Voting Results</a></li>
              <li><a href="#">My Profile</a></li>
              <li><a href="#">Candidates Profile</a></li>
              <li><a href="#">Party Profile</a></li>
              <li><a href="{% url 'charts:feedback'%}">Feedback form</a></li>
              <li><a href="{% url 'charts:report'%}">Report Problem</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        </div>
      </nav>
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="{% static 'graphs/images/vote1.jpg/' %}" alt="Voting1" width="100%" height="50%">
            </div>

    </div><br>
    {% include 'base/js.html' %}
    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock jquery %}
    })
    </script>
    <div class="contact">
           <center>
               <br><div style="color:white;font-size:20px;font-family: 'Britannic Bold'">For any queries You can contact us to the number<br><span class="glyphicon glyphicon-phone-alt"></span>+321654987,<span class="glyphicon glyphicon-earphone"></span>91201054548</div>
           </center>
           <center><a href="#"><img src="{% static 'graphs/images/twitter-logo-sketch.jpg' %}" style="height:50px;width:50px"></a>
           <a href="#"> <img src="{% static 'graphs/images/fb.jpg' %}" style="height:50px;width:50px"></a>
           <a href="#"><img src="{% static 'graphs/images/insta.jpg' %}" style="height:50px;width:50px"></a>
           <br><br><p><a href="#"><img src="{% static 'graphs/images/location.png' %}" style="height:50px;width:50px"></a><br>
           <div style="font-family: 'Britannic Bold';font-size:15px;color:red">Address:</div><span style="color:white">2town road,sricity</span></p>
           </center>
       </div>
      </div>
  </body>
</html>

main_project/templates/graphs/index3.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
  <head>
    <title>
      Django 2
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <form action ="{% url 'charts:index1' %}" method="POST">
      {% csrf_token %}
      Party:<br>
      <input type="text" name="party" id="party"><br>
      Total:<br>
      <input type="text" name="total" id="total"><br>
        <input type="submit">
    </form>
  </body>
</html>

main_project/templates/graphs/report.html
{% extends 'voters/base.html' %}
{% load staticfiles %}
{% block head %}

    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}"/>
{% endblock head %}

{%  block body %}
    <div class="feedback-page">
      <marquee id="slider" onMouseOver="this.stop()" onMouseOut="this.start()">Report Your Problem</marquee><br>
      <div class="form">
        <form class="feedback-form" action="{% url 'charts:send_email' %}" method="POST">
           {% csrf_token %}
         <h1>Report Problem</h1><br>
          <label>Report:</label>
            <textarea rows="10" id="report" name="report" placeholder="Enter Report"/></textarea>
           <label for="stars">Rate Stars:</label><br>
           <fieldset class="rating">
            <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
            <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
            <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Satisfactory - 3 stars"></label>
            <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Need to Improve - 2 stars"></label>
            <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Poor - 1 star"></label>
          </fieldset>
          <button>Submit</button>
        </form>
      </div>
</div>
<div style="height: 500px"></div>
{% endblock body %}

main_project/templates/graphs/report1.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
    <title>
        Feedback
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'graphs\css1\style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body id="reportbody" background="{% static 'graphs/images/bg8.jpg' %}"  >
<div class="feedback-page">
  <div class="form">
    <form class="feedback-form" action="{% url 'charts:send_email' %}" method="POST">
       {% csrf_token %}
     <h1>Report Problem</h1><br>
      <label>Name:</label>
      <input type="text" id="name1" name="name1" placeholder="Name"/>
      <label>Email:</label>
      <input type="email" id="email" name="email" placeholder="Email"></input>
      <label>Feedback:</label>
        <textarea rows="20" id="report" name="report" placeholder="Enter Report"/></textarea>
       <label for="stars">Rate Stars:</label><br>
       <fieldset class="rating">
        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Satisfactory - 3 stars"></label>
        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Need to Improve - 2 stars"></label>
        <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Poor - 1 star"></label>
      </fieldset>
      <button>Submit</button>
    </form>
  </div>
</div>
</body>
</html>