main_project/charts/urls.py
from django.urls import path,include,re_path
from charts import views
from django.conf.urls import url

app_name='charts'

urlpatterns=[
    url(r'^index1/',views.index1,name='index1'),
    url(r'^get_feedback/',views.get_feedback,name='get_feedback'),
    url(r'^send_email/', views.send_email, name='send_email'),
    #url(r'^$', views.index, name='index'),
    url(r'^form/', views.form, name='form'),
    url(r'^feedback/', views.feedback, name='feedback'),
    url(r'^report/', views.Report, name='report'),
    #url(r'^api/chart/data/$', views.ChartData.as_view(),name='api_data'),
    url(r'^feedback_response/', views.feedback_response, name='feedback_responses'),
]

main_project/main_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from organiser_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('evoting.urls')),
    path('evoting/', include('evoting.urls')),
    path('organiser_app/',include('organiser_app.urls')),
    path('api/candidate/',views.candidateListView.as_view()),
    path('charts/', include('charts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main_project/organiser_app/urls.py
from django.urls import path
from . import views
from evoting import views as user_views

app_name="organiser_app"

urlpatterns=[

        path('index/',views.index,name="index"),
        path('select_region_page/',views.select_region_page,name="select_region_page"),
        path('candidate/',views.candidate_page,name='candidate'),
        path('index1/',views.main_page,name='mainpage'),
        path('election/',views.election,name="election"),
        path('addelection/',views.addelection,name="addelection"),
        path('voter_region_page/search_voter', views.search_voter, name='search_voter'),
        path('voter_region_page/add_voter/', views.add_voter, name='add_voter'),
        path('voter_region_page/<int:pk>', views.voter_region_page, name='voter_region_page'),
        path('view/<int:pk>',views.candidate_view,name='candidate_view'),
        path('edit/<int:pk>',views.candidate_update,name='candidate_edit'),
        path('view1/<int:pk>',views.voter_view,name='voter_view'),
        path('edit1/<int:pk>',views.voter_update,name='voter_update'),
        path('party/',views.party,name="party"),
        path('region-candidate/<int:pk>',views.reg_candidate,name="region-candidate"),
        path('party-candidate/<str:pk>',views.party_candidate,name="party-candidate"),
        path('election-candidate/<int:pk>',views.election_candidate,name="election-candidate"),
        path('election_edit/<int:pk>',views.election_update,name="election_edit"),
        path('candidate-election/<int:pk>',views.candidate_election,name="candidate-election"),
        path('logout/', user_views.user_logout, name='evoting-logout'),
        path('srccandidate/',views.srchcandidate,name='srccandidate')
]

main_project/organiser_app/forms.py
from django import forms
from . models import Candidate,Voter,Election
from django.core import validators
import datetime


region_options = (

 ('0','AndhraPradesh') ,
 ('1','Bihar') ,
 ('2','karnataka'),
 ('3','Tamilnadu' ),
 ('4','Kerela') ,
 ('5','UttarPradesh'),
 ('6','WestBengal') ,
 ('7','MadhyaPradesh') ,
 ('8','Haryana') ,
 ('9','Assam'),
 ('10','All')

)

party_options=(

    ('BJP','Bhartiya Janta Party'),
    ('CPI','Communist Party of India'),
    ('INC','Indian National Congress'),
    ('AAP','Aam Aadmi Party') ,
    ('TDP','Telugu Desam Party'),
    ('SS','Shiv Sena') ,
    ('TRS','Telangana Rashtra Samithi'),
    ('JD','Janata Dal') ,
    ('SP','Samajwadi Party') ,
   ('RJD', 'Rashtriya Janata Dal')

)





class Candidateform(forms.ModelForm):
    candidate_dob = forms.DateField(widget=forms.SelectDateWidget(years=range(1920, 1994)))

    class Meta:
        model = Candidate
        fields = ('candidate_name','candidate_fname','candidate_party','candidate_region','candidate_gender','candidate_email','candidate_dob','candidate_aadhar','profile_pic')



class Electionform(forms.ModelForm):
    date_of_start = forms.DateField(widget=forms.SelectDateWidget(),initial=datetime.date.today)
    date_of_end = forms.DateField(widget=forms.SelectDateWidget(),initial=datetime.date.today)
    class Meta():
        model=Election
        fields=('election_type','election_year','date_of_start','date_of_end', 'candidates')



class Voterform(forms.ModelForm):
    voter_dob = forms.DateField(widget=forms.DateInput(attrs={'id':'date','type':'date',}))
    voter_age = forms.IntegerField(widget=forms.NumberInput(attrs={'id':'age'}))

    class Meta:
        model = Voter
        fields = '__all__'


class RegionForm(forms.Form):
    select_region = forms.ChoiceField(choices=region_options)

class PartyForm(forms.Form):
    select_party=forms.ChoiceField(choices=party_options)

main_project/organiser_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . forms import *
from . models import *
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from  organiser_app.serializers import  CandidateSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.contrib import messages
import schedule
import time
import datetime

region_options={

 '0':'AndhraPradesh' ,
 '1':'Bihar' ,
 '2':'karnataka',
 '3':'Tamilnadu' ,
 '4':'Kerela' ,
 '5':'UttarPradesh',
 '6':'WestBengal' ,
 '7':'MadhyaPradesh' ,
 '8':'Haryana' ,
 '9':'Assam',
 '10':'All'

}


# Create your views here.
@login_required
def party(request):
    party_form = PartyForm()
    context = {'party_form':party_form}
    return render(request, 'organiser_app/party.html',context)



@login_required
def index(request):
    region_form = RegionForm()
    context = {'region_form':region_form}
    return render(request, 'organiser_app/index.html',context)

@login_required
def srchcandidate(request):
    candidate_id=request.POST.get('Candidateid')

    try:
        object = Candidate.objects.get(candidate_id=candidate_id)
        region=region_options[object.candidate_region]
        context = {'object': object,'region':region}
        return render(request, 'organiser_app/candidate_info.html', context=context)
    except:
        message ='Sorry,' + 'Candidate Id "' + str(candidate_id) + '" does not exist.'
        context = {'message': message}
        return render(request, 'organiser_app/candidate_info.html', context=context)

    return render(request,'organiser_app/index.html',context)

@login_required
def candidate_page(request):

    if request.method =="POST":
        candidate_form=Candidateform(request.POST, request.FILES)

        if candidate_form.is_valid():

            object=candidate_form.save()
            region=region_options[object.candidate_region]
            context={'object':object,'region':region}
            return render(request,'organiser_app/candidate_info.html',context)

        else:
            print(candidate_form.errors)

    else:
        candidate_form=Candidateform()

    return render(request, 'organiser_app/addcandidate.html', {'candidate_form':candidate_form })

@login_required
def main_page(request):
    return render(request,'organiser_app/index1.html')

#change

@login_required
def election(request):
    region=[]
    election_instance=Election.objects.all()
    for election in election_instance:
        region.append(Election_region.objects.get(election=election.election_id))
    election_region = zip(election_instance, region)

    context={'election_region':election_region}
    return render(request,'organiser_app/election.html',context)

# ------------------------------------Voter Code--------------------------------------------

@login_required
def add_voter(request):

    if request.method == 'POST':

        voter_form = Voterform(data=request.POST)

        if voter_form.is_valid():

                voter_form.save(commit=True)
                message = 'Voter is added successfully!'
                return render(request, 'organiser_app/add_voter.html', {'voter_form': voter_form, 'message': message})

        else:
            print(voter_form.errors)
    else:
        voter_form = Voterform()

    return render(request, 'organiser_app/add_voter.html', {'voter_form':voter_form})

@login_required
def select_region_page(request):

    region_form = RegionForm()

    context = {'region_form':region_form}

    return render(request, 'organiser_app/select_region.html',context)

@login_required
def search_voter(request):

    if request.method == 'POST':
        voterid = request.POST.get('voterid')
        try:
            voter = Voter.objects.get(voter_id=voterid)
            context = {'voter': voter}
            return render(request, 'organiser_app/search_results.html', context=context)
        except:
            message = 'Voter Id "' + str(voterid) + '" does not exist.'
            context = {'message': message}
            return render(request, 'organiser_app/search_results.html', context=context)

    return render(request, 'organiser_app/search_results.html')

@login_required
def voter_region_page(request,pk):
    template_name='organiser_app/voters_list.html'
    if pk is 10:
        voters=Voter.objects.all()
    else:
        voters = Voter.objects.filter(voter_region=pk)
    context = {'voters':voters}
    return render(request,template_name,context)

@login_required
def voter_view(request, pk):
    template_name = 'organiser_app/voter_info.html'
    voter=get_object_or_404(Voter, pk=pk)
    region = region_options[voter.voter_region]
    context = {'voter': voter, 'region': region}
    return render(request, template_name, context=context)

@login_required
def voter_update(request, pk):
    template_name = 'organiser_app/update_voter_form.html'
    voter = get_object_or_404(Voter, pk=pk)
    voter_form = Voterform(request.POST or None, instance=voter)
    if request.method == 'POST':
        if voter_form.is_valid():
            voter_form.save()
            message = 'Voter Id "' + str(voter.voter_id) + '" is updated successfully!'
            return render(request, template_name, {'voter_form': voter_form, 'message': message})
    return render(request, template_name, {'voter_form': voter_form})


def search_voter(request):

    if request.method == 'POST':
        voterid = request.POST.get('voterid')
        try:
            voter = Voter.objects.get(voter_id=voterid)
            context = {'voter': voter}
            return render(request, 'organiser_app/search_results.html', context=context)
        except:
            message = 'Voter Id "' + str(voterid) + '" does not exist.'
            context = {'message': message}
            return render(request, 'organiser_app/search_results.html', context=context)

    return render(request, 'organiser_app/search_results.html')


#-------------------------------------------End Voter Code---------------------------------------------
#change

@login_required
def addelection(request):
    if request.method=="POST":
        addelection_form=Electionform(data=request.POST)

        if addelection_form.is_valid():
            election_instance = addelection_form.save()

            for candidate in election_instance.candidates.all():

                candidate_election_instance = Candidate_election()
                candidate_election_instance.candidate = candidate
                candidate_election_instance.election = election_instance
                candidate_election_instance.save()

            if election_instance.election_type == 'P':

                election_region_instance=Election_region()
                election_region_instance.region="All"
                election_region_instance.election=election_instance
                election_region_instance.save()

            if election_instance.election_type=='A':
                election_region_instance=Election_region()
                region=request.POST['statelist']
                print(region)
                election_region_instance.region=region
                election_region_instance.election=election_instance
                election_region_instance.save()

            region=[]
            election_instance=Election.objects.all()
            for election in election_instance:
                region.append(Election_region.objects.get(election=election.election_id))
            election_region = zip(election_instance, region)

            context={'election_region':election_region}
            return render(request,'organiser_app/election.html',context)

        else:
            print(addelection_form.errors)
    else:
        addelection_form=Electionform()

    return render(request,'organiser_app/election_form.html',{'addelection_form':addelection_form })

@login_required
def candidate_view(request,pk):
    template_name='organiser_app/candidate_detail.html'
    candidate=get_object_or_404(Candidate,pk=pk)
    region=region_options[candidate.candidate_region]
    context={'object':candidate, 'region':region}
    return render(request,template_name,context=context)

@login_required
def candidate_update(request,pk):
    template_name='organiser_app/candidate_form.html'
    candidate=get_object_or_404(Candidate,pk=pk)
    form=Candidateform(request.POST or None,instance=candidate)
    if request.method=="POST":

        if form.is_valid():
            object=form.save()

            region=region_options[object.candidate_region]
            context={'object':object,'region':region}
            return render(request,'organiser_app/candidate_info.html',context)

            #return HttpResponseRedirect(reverse( organiser_app:candidate_edit 'form.candidate_id ))

    return render(request,template_name,{'form':form})

#change
@login_required
def reg_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    if pk is 10:
        candidates=Candidate.objects.all()

    else:
        candidates=Candidate.objects.filter(candidate_region=pk)

    context={'candidates':candidates}
    return render(request,template_name,context)

@login_required
def party_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    candidates=Candidate.objects.filter(candidate_party=pk)
    context={'candidates':candidates}
    return render(request,template_name,context)


@login_required
def election_candidate(request,pk):
    template_name='organiser_app/region_candidate.html'
    candidates_ele=Candidate_election.objects.filter(election=pk)
    list_candidate=[]
    for candi in candidates_ele:
        list_candidate.append(candi.candidate)

main_project/organiser_app/templates/organiser_app/candidate_detail.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      a:hover {
        background: #263238;

      }

      .table-container{
      -webkit-box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
      -moz-box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
      box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
      width:375px;
      height:743px;
      margin-left: -30px;
      margin-top:20px;
      }


    </style>

    <title>organiser_region</title>
  </head>

    <body style="position:relative; padding-top: 20px">



        <nav class="navbar fixed-top container-fluid navbar-expand-lg navbar-light bg-dark" style="background-color:#008B8B" >


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
              <p style="color:white; font-size:30px;margin:5px"><a style="color:white;text-decoration: none" href="{% url 'evoting-home' %}" >E-Voting </a></p>


            </div>
              <ul class=" nav navbar-nav navbar-right">
                <li class="nav-item active">
                  <a class="nav-link text-white" href="{% url "organiser_app:mainpage" %}" style="font-size:26px">Mainpage <span class="sr-only">(current)</span></a>
                </li>

                <li>

                  <p class="text-white " style="font-size:26px;margin:5px">|</p>
                </li>


                <li class="nav-item active">
                  <a class="nav-link text-white" href="{% url "organiser_app:candidate_edit" object.candidate_id %}" style="font-size:26px">Update <span class="sr-only">(current)</span></a>
                </li>

                <li>

                  <p class="text-white " style="font-size:26px;margin:5px">|</p>
                </li>



                <li class="nav-item active">
                  <a class="nav-link text-white" href="{% url 'organiser_app:evoting-logout'%}" style="font-size:26px">Logout <span class="sr-only">(current)</span></a>
                </li>

              </ul>



          </nav>


  </div>

  <div style="margin-top:60px">
          {% if object %}
          <div class="container-fluid h-100 text-dark " style="margin-top:100px">
                  <div class="row justify-content-center align-items-center h-100 ">
                          <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3 ">
          <div class="table-container">
          <div style="font-size:40px;" class="bg-primary text-white pl-3">Candidate Info</div>

          {% if object.profile_pic %}
           <img class="card-img-top" src="{{ object.profile_pic.url }}" alt="Card image cap" width="50" height="200">
             {% else %}
               <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="Card image cap" width="50" height="200">
               {% endif %}

          <table class="table table-dark"
              <tr>
                  <th> Candidate Id</th>
                  <td>{{ object.candidate_id}}</td>
              </tr>
              <tr>
                  <th> Candidate Name</th>
                  <td>{{ object.candidate_name}}</td>
              </tr>
              <tr>
                  <th> Candidate Father</th>
                  <td>{{ object.candidate_fname}}</td>
              </tr>
              <tr>
                  <th> Candidate email</th>
                  <td>{{ object.candidate_email}}</td>
              </tr>
              <tr>
                  <th> Candidate DOB</th>
                  <td>{{ object.candidate_dob}}</td>
              </tr>
              <tr>
                  <th> Candidate Region</th>
                  <td>{{ region }}</td>
              </tr>
              <tr>
                  <th> Candidate Aadhar</th>
                  <td>{{ object.candidate_aadhar}}</td>
              </tr>
              <tr>
                  <th> Candidate gender</th>
                  <td>{{ object.candidate_gender}}</td>
              </tr>
              <tr>
                  <th> Candidate Party</th>
                  <td>{{ object.candidate_party}}</td>
              </tr>

              <tr>
                  <th> Election Info</th>
                  <td><a href="{% url "organiser_app:candidate-election" object.candidate_id %}">Click</a></td>
              </tr>




  </table>
</table>
</div>
</div>
</div>
              {% endif %}
  </div>


  </body>
</html>

main_project/organiser_app/templates/organiser_app/candidate_form.html
{% load staticfiles %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      a:hover {
        background: #263238;

      }

      .input100{
        border-radius:5px;
        padding:3px;
        background-color:#e0e0e0;
        border:none;
        width:300px;
        outline:none;


      }


.form-container{
  -webkit-box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
-moz-box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
box-shadow: 1px 5px 15px 9px rgba(0,0,0,0.75);
width:375px;
height:660px;
margin-left: -30px;
margin-top:20px;
}

.bord{
  border:1px solid #263238;
}

    </style>

    <title>organiser_region</title>
  </head>

  <body style="background-image:url({% static 'images/back.jpg' %});background-repeat: no-repeat;height:100%;background-attachment:fixed" >



      <nav class="navbar fixed-top container-fluid navbar-expand-lg navbar-light bg-dark" style="background-color:#008B8B" >


              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>


          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <img src="{% static "images/e-voting.png"%}" alt="evoting image" width="50" height="50">
            <p style="color:white; font-size:30px;margin:5px"><a style="color:white;text-decoration: none" href="{% url 'evoting-home' %}" >E-Voting </a></p>


          </div>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:mainpage' %}" style="font-size:26px">Mainpage <span class="sr-only">(current)</span></a>
              </li>

              <li>

                <p class="text-white " style="font-size:26px;margin:5px">|</p>
              </li>


              <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:select_region_page' %}" style="font-size:26px">VoterPage<span class="sr-only">(current)</span></a>
              </li>

              <li>

                <p class="text-white " style="font-size:26px;margin:5px">|</p>
              </li>


              <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'organiser_app:evoting-logout'%}" style="font-size:26px">Logout <span class="sr-only">(current)</span></a>
              </li>

            </ul>


        </nav>


        <div class="container-fluid h-100 text-dark " style="margin-top:100px">
                <div class="row justify-content-center align-items-center h-100 ">
                        <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">

                  <div style="margin-left:30px" >
                <form method="post" action=" " class="form-container">
                  <div style="margin-left:25px;margin-top:40px;">

                  {% csrf_token %}

                <div class="form-group row ">
                 <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px;color:white;margin:5px">Candidate Name</label>
                </div>
                <div class="form-group row" style="margin-top:-32px">
                <div class="col-sm-12">
                  {{ form.candidate_name|attr:"placeholder:Enter Candidate Name"|attr:"width:200px"|add_class:"input100" }}
                </div>
                 </div>

                 <div class="form-group row" style="margin-top:-10px">
                        <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px;margin:5px ;color:white">Father's Name</label>
                    </div>
                       <div class="form-group row" style="margin-top:-31px">
                       <div class="col-sm-12">
                        {{ form.candidate_fname|attr:"placeholder:Enter Father's Name"|attr:"width:200px"|add_class:"input100" }}
                       </div>
                        </div>

                        <div class="form-group row" style="margin-top:-10px">
                               <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px ;margin:5px;color:white;">Aadhar number</label>
                           </div>


                        <div class="form-group row" style="margin-top:-30px">
                        <div class="col-sm-12">
                         {{ form.candidate_aadhar|attr:"placeholder:Enter aadhar number"|attr:"width:200px"|add_class:"input100" }}
                        </div>
                         </div>



                        <div class="form-group row" style="margin-top:-10px">
                                <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px;margin:5px ;margin:6px;color:white;">Email</label>
                            </div>
                               <div class="form-group row" style="margin-top:-32px">
                               <div class="col-sm-12">
                                {{ form.candidate_email|attr:"placeholder:Enter Email Id"|attr:"width:200px"|add_class:"input100"}}
                               </div>
                                </div>



                    <fieldset class="form-group" style="margin-top:-10px">
                  <div class="row">
                    <legend class="col-form-label col-sm-12 pt-0" style="font-size:18px;margin:5px;color:white;" >Gender</legend>
                  </div>
                  <div style="margin-top:-15px">
                  {{form.candidate_gender|add_class:"input100"}}
                </div>
                </fieldset>
                <div class="form-group row" style="margin-top:-15px">
                        <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px;margin:5px;color:white;">Date of Birth</label>
                </div>



                    <div class="form-group row" style="margin-top:-30px">
                       <div class="col-sm-12">
                        {{form.candidate_dob|add_class:"input100"|add_class:"bord"}}
                       </div>
                     </div>

                     <div class="form-group row" style="margin-top:-15px">
                            <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px;margin:5px;color:white;">Select Party</label>
                    </div>





                     <div class="form-group" style="margin-top:-30px">
                      {{form.candidate_party|add_class:"input100"}}

                          </div>

                          <div class="form-group row" style="margin-top:-10px">
                                  <label for="inputEmail3" class="col-sm-12 col-form-label" style="font-size:18px ;margin:3px;color:white;">Candidate Region</label>
                          </div>
                          <div class="form-group row" style="margin-top:-30px">
                          <div class="col-sm-12">
                          {{ form.candidate_region|attr:"width:200px"|add_class:"input100" }}
                          </div>
                          </div>



                <div class="form-group row" >
                  <div class="col-sm-12">
                <button type="submit" class="btn btn-danger"style="margin-left:5px;border-radius:5px;margin-top:5px;width:100px">Submit</button>
                </div>
                </div>
              </div>

              </form>

            </div>

        </div>
        </div>
        </div>


           <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>



  </body>
</html>